name: 'gogo-dev'
version: '3'
services:
  # gogo-client-dev:
  #   container_name: gogo-client-dev
  #   image: seantokuzo/gogo-client
  #   ports:
  #     - '5150:5150'
  #   volumes:
      
  #   depends_on:
  #     gogo-server-dev:
  #       condition: service_healthy
  #   command: npm run dev

  gogo-dev:
    container_name: gogo-dev
    image: seantokuzo/gogo-dev
    ports:
      - 5150:5150
    # healthcheck:
    #   test: curl -f http://localhost:3000/api/v1/user/ || exit 1
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    #   start_interval: 5s
    # network_mode: host
    environment:
      - JWT_SECRET=poopityscoopityDERPDEEDOO
      - JWT_LIFETIME=1d
      - MONGO_URI=mongodb://gogo-mongo-dev:27017/gogo-testdb
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./client:/usr/src/app/client
      - client_node_modules:/usr/src/app/client/node_modules
      - ./server:/usr/src/app/server
      - server_node_modules:/usr/src/app/server/node_modules
    depends_on:
      - gogo-mongo-dev
    command: npm run dev

  gogo-mongo-dev:
    container_name: gogo-mongo-dev
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: gogo-testdb
    volumes:
      - mongo-dev-volume:/data/db
    command: mongod --quiet --logpath /dev/null

volumes:
  client_node_modules:
  server_node_modules:
  mongo-dev-volume:
