name: 'gogo-test'
services:
  # Application Test Service
  gogo-test:
    container_name: gogo-test
    image: seantokuzo/gogo-dev
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - JWT_SECRET=testJwtSecret
      - JWT_LIFETIME=1d
      - JWT_CONFIRM_LIFETIME=1d
      - DEV_EMAIL_USERNAME=${DEV_EMAIL_USERNAME}
      - DEV_EMAIL_PASSWORD=${DEV_EMAIL_PASSWORD}
      - DEV_EMAIL_HOST=${DEV_EMAIL_HOST}
      - DEV_EMAIL_PORT=${DEV_EMAIL_PORT}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gogo-testdb
      - POSTGRES_PASSWORD=gogo-test
      - POSTGRES_HOST=gogo-pg-test
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - TEST_COMMAND=${TEST_COMMAND}
    volumes:
      - ./client:/usr/src/app/client
      - ./:/usr/src/app
      - client_test_node_modules:/usr/src/app/client/node_modules
      - server_test_node_modules:/usr/src/app/node_modules
    depends_on:
      - gogo-pg-test
    command: npm run ${TEST_COMMAND}
  # Test Postgres Service
  gogo-pg-test:
    container_name: gogo-pg-test
    image: postgres:16.3
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gogo-testdb
      - POSTGRES_PASSWORD=gogo-test
    volumes:
      - ./scripts/db/postgres/pg_init.sql:/docker-entrypoint-initdb.d/pg_init.sql

volumes:
  client_test_node_modules:
  server_test_node_modules:
