name: build-tests
on:
  pull_request:
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Pull Docker Image
        run: docker pull seantokuzo/gogo-dev
      - name: Run Linting
        run: LINT_COMMAND=lint docker compose -f docker-compose-lint.yml up --abort-on-container-exit
  unit-testing:
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Pull Docker Image
        run: docker pull seantokuzo/gogo-dev
      - name: Run Unit Tests
        run: TEST_COMMAND=test:silent docker compose -f docker-compose-test.yml up --abort-on-container-exit
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_LIFETIME: 1d
          MONGO_URI: mongodb://gogo-mongo-test:27017/gogo-testdb
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URL: ${{ secrets.GOOGLE_REDIRECT_URL }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
